import {PackedBinaryDataFactory} from './binary-data.mjs';
import * as pdfjs from './vendor/pdf.mjs';
import {normalizeRect,validRect,createRedactedPdf} from './redact.mjs';
pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.mjs',import.meta.url).href;
const $=id=>document.getElementById(id);
let doc=null,filename='',current=1,masks={},history=[],selected=-1,zoom=1,baseWidth=0,baseHeight=0,busy=false,renderTask=null,renderVersion=0,drag=null,loadTask=null;
function count(){return Object.values(masks).reduce((n,a)=>n+a.length,0);}
function message(text=''){ $('status').textContent=text; }
function showError(text){$('error').textContent=text;$('error').hidden=!text;}
function lock(value){busy=value;document.body.classList.toggle('busy',value);for(const id of ['open','demo','change','save','prev','next','undo','clear','zoomout','zoomin','fit'])$(id).disabled=value;refresh();}
function checkpoint(){history.push(JSON.parse(JSON.stringify(masks)));if(history.length>100)history.shift();}
function undo(){if(busy||!history.length)return;masks=history.pop();selected=-1;refresh();}
function pageMasks(){return masks[current]||[];}
function setRectStyle(el,r){Object.assign(el.style,{left:r.x*100+'%',top:r.y*100+'%',width:r.w*100+'%',height:r.h*100+'%'});}
function refresh(){if(!doc)return;$('pagecount').textContent=doc.numPages;$('currentpage').textContent=`${current} / ${doc.numPages} ページ`;$('total').textContent=`全体 ${count()} か所`;$('maskcount').textContent=pageMasks().length;$('maskempty').hidden=pageMasks().length>0;$('save').disabled=busy||count()===0;$('undo').disabled=busy||!history.length;$('clear').disabled=busy||!pageMasks().length;$('prev').disabled=busy||current===1;$('next').disabled=busy||current===doc.numPages;$('zoomout').disabled=busy||zoom<=.4;$('zoomin').disabled=busy||zoom>=2.5;$('zoomlabel').textContent=Math.round(zoom*100)+'%';$('pages').replaceChildren();for(let n=1;n<=doc.numPages;n++){const button=document.createElement('button');button.className='page-button'+(n===current?' active':'');button.disabled=busy;button.setAttribute('aria-current',n===current?'page':'false');const number=document.createElement('span');number.className='page-number';number.textContent=n;button.append(number,document.createTextNode('ページ'));if(masks[n]?.length){const badge=document.createElement('span');badge.className='badge';badge.setAttribute('aria-label',`${masks[n].length}か所選択済み`);button.append(badge);}button.onclick=()=>goPage(n);$('pages').append(button);}
$('overlay').replaceChildren();$('masks').replaceChildren();pageMasks().forEach((r,i)=>{const box=document.createElement('button');box.className='mask'+(selected===i?' selected':'');box.setAttribute('aria-label',`黒塗り範囲 ${i+1} を選択`);setRectStyle(box,r);box.onclick=e=>{e.stopPropagation();selectMask(i);};box.onpointerdown=e=>e.stopPropagation();$('overlay').append(box);const row=document.createElement('div');row.className='mask-row'+(selected===i?' active':'');const button=document.createElement('button');button.className='mask-select';const chip=document.createElement('span');chip.className='mask-chip';button.append(chip,document.createTextNode(`範囲 ${i+1}`));button.onclick=()=>selectMask(i);const remove=document.createElement('button');remove.className='mask-remove';remove.textContent='×';remove.setAttribute('aria-label',`範囲 ${i+1} を削除`);remove.disabled=busy;remove.onclick=()=>removeMask(i);button.disabled=busy;row.append(button,remove);$('masks').append(row);});}
function selectMask(i){if(busy)return;selected=i;refresh();}
function removeMask(i){if(busy||!pageMasks()[i])return;checkpoint();masks[current].splice(i,1);selected=-1;refresh();}
function addMask(page,r){if(busy||!doc)throw Error('PDFを開いてから操作してください。');if(!Number.isInteger(page)||page<1||page>doc.numPages||!validRect(r))throw Error('ページまたは選択範囲が無効です。');checkpoint();(masks[page]??=[]).push({...r});selected=page===current?masks[page].length-1:-1;refresh();return {page,regions:masks[page].length,total:count()};}
function sizePaper(){if(!baseWidth)return;const width=Math.max(1,baseWidth*zoom);$('paper').style.width=width+'px';$('paper').style.height=baseHeight*zoom+'px';$('paper').style.margin=width>$('scrollarea').clientWidth-40?'0':'0 auto';$('zoomlabel').textContent=Math.round(zoom*100)+'%';}
function fit(){if(busy||!doc)return;zoom=Math.max(.15,Math.min(2.5,($('scrollarea').clientWidth-(window.innerWidth<780?32:56))/baseWidth));sizePaper();refresh();}
async function renderPage(autoFit=false){const version=++renderVersion;if(renderTask){renderTask.cancel();try{await renderTask.promise;}catch{}}$('rendering').hidden=false;try{const page=await doc.getPage(current);if(version!==renderVersion)return;const base=page.getViewport({scale:1});baseWidth=base.width;baseHeight=base.height;const scale=Math.min(2,Math.sqrt(10000000/(base.width*base.height)));const viewport=page.getViewport({scale});const temp=document.createElement('canvas');temp.width=Math.ceil(viewport.width);temp.height=Math.ceil(viewport.height);const task=page.render({canvasContext:temp.getContext('2d',{alpha:false}),viewport,annotationMode:1,background:'#ffffff'});renderTask=task;await task.promise;if(version!==renderVersion)return;const canvas=$('canvas');canvas.width=temp.width;canvas.height=temp.height;canvas.getContext('2d').drawImage(temp,0,0);renderTask=null;temp.width=1;temp.height=1;if(autoFit)fit();else sizePaper();refresh();}catch(e){if(e.name!=='RenderingCancelledException')showError('このページを表示できませんでした。別のページを選ぶか、PDFを開き直してください。');}finally{if(version===renderVersion)$('rendering').hidden=true;}}
async function goPage(n){if(busy||n===current)return;cancelDrag();current=n;selected=-1;refresh();await renderPage();$('scrollarea').scrollTop=0;}
function passwordPrompt(update,reason){const dlg=$('passwordDialog');$('passwordHint').textContent=reason===pdfjs.PasswordResponses.INCORRECT_PASSWORD?'パスワードが違います。もう一度入力してください。':'このPDFを開くためのパスワードを入力してください。';$('password').value='';dlg.returnValue='';dlg.onclose=()=>{if(dlg.returnValue==='open')update($('password').value);else loadTask?.destroy();};if(!dlg.open)dlg.showModal();$('password').focus();}
async function openBytes(bytes,name){if(busy)return;lock(true);showError('');message('PDFを読み込み中…');const old=doc;try{loadTask=pdfjs.getDocument({data:bytes,BinaryDataFactory:PackedBinaryDataFactory,useWorkerFetch:false,cMapUrl:new URL('./vendor/cmaps/',import.meta.url).href,cMapPacked:true,standardFontDataUrl:new URL('./vendor/standard_fonts/',import.meta.url).href,wasmUrl:new URL('./vendor/wasm/',import.meta.url).href,isEvalSupported:false});loadTask.onPassword=passwordPrompt;const nextDoc=await loadTask.promise;if(renderTask){renderTask.cancel();try{await renderTask.promise;}catch{}}doc=nextDoc;filename=name;current=1;masks={};history=[];selected=-1;$('filename').textContent=name;$('docinfo').textContent=`${doc.numPages}ページ · ドラッグで隠す範囲を選択`;$('welcome').hidden=true;$('editor').hidden=false;lock(false);await renderPage(true);if(old)await old.destroy();message('');}catch(e){const cancelled=/destroy|abort/i.test(e.message||'');if(!cancelled)showError('PDFを開けませんでした。ファイルが破損していないか、PDF形式であるかを確認してください。');message('');}finally{loadTask=null;lock(false);}}
async function openFile(file){if(!file||busy)return;if(!/\.pdf$/i.test(file.name)&&file.type!=='application/pdf'){showError('PDFファイルを選択してください。');return;}if(file.size>100*1024*1024){showError('100MB以下のPDFを選択してください。');return;}try{await openBytes(new Uint8Array(await file.arrayBuffer()),file.name);}catch{showError('ファイルを読み込めませんでした。もう一度選択してください。');}}
function point(e){const b=$('overlay').getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-b.left)/b.width)),y:Math.max(0,Math.min(1,(e.clientY-b.top)/b.height))};}
function cancelDrag(){if(!drag)return;drag.el.remove();drag=null;}
$('overlay').onpointerdown=e=>{if(busy||!doc||!$('rendering').hidden||e.button!==0)return;cancelDrag();e.preventDefault();const el=document.createElement('div');el.className='mask draft';const start=point(e);drag={start,el,pointer:e.pointerId};$('overlay').append(el);setRectStyle(el,{...start,w:0,h:0});$('overlay').setPointerCapture(e.pointerId);};
$('overlay').onpointermove=e=>{if(drag?.pointer!==e.pointerId)return;setRectStyle(drag.el,normalizeRect(drag.start,point(e)));};
$('overlay').onpointerup=e=>{if(drag?.pointer!==e.pointerId)return;const r=normalizeRect(drag.start,point(e));const bounds=$('overlay').getBoundingClientRect();cancelDrag();if(r.w*bounds.width>=3&&r.h*bounds.height>=3)addMask(current,r);};
$('overlay').onpointercancel=cancelDrag;$('overlay').onlostpointercapture=cancelDrag;
$('file').onchange=e=>{openFile(e.target.files[0]);e.target.value='';};for(const id of ['open','change'])$(id).onclick=()=>$('file').click();
for(const event of ['dragenter','dragover'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.add('dragover');});for(const event of ['dragleave','drop'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.remove('dragover');});$('dropzone').addEventListener('drop',e=>openFile(e.dataTransfer.files[0]));
// Prevent browser navigation when a file is dropped outside the welcome target.
document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',e=>e.preventDefault());
$('undo').onclick=undo;$('clear').onclick=()=>{if(busy||!pageMasks().length)return;checkpoint();masks[current]=[];selected=-1;refresh();};$('prev').onclick=()=>goPage(current-1);$('next').onclick=()=>goPage(current+1);$('zoomout').onclick=()=>{zoom=Math.max(.4,zoom-.15);sizePaper();refresh();};$('zoomin').onclick=()=>{zoom=Math.min(2.5,zoom+.15);sizePaper();refresh();};$('fit').onclick=fit;$('cancelPassword').onclick=()=>$('passwordDialog').close('cancel');
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,dialog'))return;if(e.key==='Escape')cancelDrag();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();}if((e.key==='Delete'||e.key==='Backspace')&&selected>=0){e.preventDefault();removeMask(selected);}});
async function save(){if(busy||!doc||!count())throw Error('黒塗り範囲を選択してください。');cancelDrag();if(renderTask){try{await renderTask.promise;}catch{}}lock(true);showError('');$('save').textContent='PDFを作成中…';try{const bytes=await createRedactedPdf(doc,masks,{PDFDocument:PDFLib.PDFDocument,createCanvas:(w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c;},canvasToPng:c=>new Promise((resolve,reject)=>c.toBlob(async b=>{try{if(!b)throw Error('画像に変換できませんでした。');resolve(new Uint8Array(await b.arrayBuffer()));}catch(e){reject(e);}},'image/png')),onProgress:(n,total)=>message(`黒塗りPDFを作成中… ${n} / ${total} ページ`)});const blob=new Blob([bytes],{type:'application/pdf'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename.replace(/\.pdf$/i,'')+'_黒塗り.pdf';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);message('黒塗りしたPDFを保存しました。開いて仕上がりを確認してください。');return {filename:filename.replace(/\.pdf$/i,'')+'_黒塗り.pdf',pages:doc.numPages,regions:count()};}catch(e){showError('PDFを保存できませんでした。大きいPDFの場合はページ数を減らしてお試しください。');message('');throw e;}finally{$('save').textContent='黒塗りして保存';lock(false);}}
$('save').onclick=()=>save().catch(()=>{});
$('demo').onclick=async()=>{try{const p=await PDFLib.PDFDocument.create();p.setTitle('Sample statement');for(let n=1;n<=2;n++){const page=p.addPage([595,842]);const font=await p.embedFont(PDFLib.StandardFonts.Helvetica);const draw=(t,x,y,size=12)=>page.drawText(t,{x,y,size,font,color:PDFLib.rgb(.13,.18,.27)});draw('SAMPLE CARD',44,785,23);draw('MONTHLY STATEMENT',44,754,12);draw('Demonstration data - no real account information',44,727,10);draw('NAME: TAKUMI SAMPLE',44,680,14);draw('CARD: 1234 5678 9012 3456',44,653,14);draw('DATE',44,587);draw('DESCRIPTION',152,587);draw('AMOUNT (JPY)',420,587);const rows=[['2026/09/01','OSAKA COFFEE','580'],['2026/09/04','SAMPLE BOOKSTORE','2,640'],['2026/09/09','SAMPLE SUPERMARKET','3,120'],['2026/09/12','SAMPLE RAILWAY','1,480'],['2026/09/18','ONLINE STORE','4,980']];rows.forEach((r,i)=>{const y=553-i*48;r.forEach((v,j)=>draw(v,[44,152,454][j],y));page.drawLine({start:{x:44,y:y-16},end:{x:552,y:y-16},thickness:.5,color:PDFLib.rgb(.8,.83,.87)});});draw('TOTAL: 12,800 JPY',354,275,17);draw(`PAGE ${n} / 2`,44,40,10);}await openBytes(await p.save(),'サンプル明細.pdf');}catch{showError('サンプルを読み込めませんでした。');}};
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(doc&&!busy)sizePaper();},100);});
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const tool=(name,description,inputSchema,execute,readOnlyHint=false)=>{try{Promise.resolve(context.registerTool({name,description,inputSchema,execute,annotations:{readOnlyHint,untrustedContentHint:false}},{signal:lifecycle.signal})).catch(()=>{});}catch{}};tool('get_pdf_redaction_state','開いているPDFのページ数と選択範囲を確認します。元の明細の文字は返しません。',{type:'object',properties:{},additionalProperties:false},()=>({loaded:!!doc,pages:doc?.numPages||0,currentPage:current,regions:JSON.parse(JSON.stringify(masks)),busy}),true);tool('add_pdf_redaction','開いているPDFに黒塗り範囲を追加します。座標はページ左上を原点とする0〜1の比率です。保存は行いません。',{type:'object',properties:{page:{type:'integer',minimum:1},x:{type:'number',minimum:0,maximum:1},y:{type:'number',minimum:0,maximum:1},w:{type:'number',exclusiveMinimum:0,maximum:1},h:{type:'number',exclusiveMinimum:0,maximum:1}},required:['page','x','y','w','h'],additionalProperties:false},input=>addMask(input.page,{x:input.x,y:input.y,w:input.w,h:input.h}));tool('download_redacted_pdf','選択範囲を黒塗りした画像のみのPDFを作成し、端末へダウンロードします。',{type:'object',properties:{},additionalProperties:false},()=>save());}
